[2023-12-05T14:00:07.183+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_hook_v2.upload_to_s3 scheduled__2023-12-04T03:00:00+00:00 [queued]>
[2023-12-05T14:00:07.209+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_hook_v2.upload_to_s3 scheduled__2023-12-04T03:00:00+00:00 [queued]>
[2023-12-05T14:00:07.213+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-12-05T14:00:07.246+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2023-12-04 03:00:00+00:00
[2023-12-05T14:00:07.255+0000] {standard_task_runner.py:57} INFO - Started process 15371 to run task
[2023-12-05T14:00:07.260+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_hook_v2', 'upload_to_s3', 'scheduled__2023-12-04T03:00:00+00:00', '--job-id', '356', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_with_hook.py', '--cfg-path', '/tmp/tmpicpsr9bj']
[2023-12-05T14:00:07.265+0000] {standard_task_runner.py:85} INFO - Job 356: Subtask upload_to_s3
[2023-12-05T14:00:07.338+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_with_hook_v2.upload_to_s3 scheduled__2023-12-04T03:00:00+00:00 [running]> on host 0c998a8be895
[2023-12-05T14:00:07.513+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='debora' AIRFLOW_CTX_DAG_ID='dag_with_hook_v2' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2023-12-04T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-04T03:00:00+00:00'
[2023-12-05T14:00:07.534+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:206 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-12-05T14:00:07.554+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-12-05T14:00:07.571+0000] {logging_mixin.py:154} INFO - connected to postgres
[2023-12-05T14:00:07.589+0000] {dag_with_postgres_with_hook.py:29} INFO - Saved get_orders_2023-12-04T03:00:00+00:00
[2023-12-05T14:00:07.592+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-12-05T14:00:07.628+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_hook_v2, task_id=upload_to_s3, execution_date=20231204T030000, start_date=20231205T140007, end_date=20231205T140007
[2023-12-05T14:00:07.716+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-05T14:00:07.743+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
