[2023-12-05T14:00:28.509+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_hook_v2.upload_to_s3 manual__2023-12-05T14:00:27.237943+00:00 [queued]>
[2023-12-05T14:00:28.549+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_hook_v2.upload_to_s3 manual__2023-12-05T14:00:27.237943+00:00 [queued]>
[2023-12-05T14:00:28.550+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-12-05T14:00:28.571+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2023-12-05 14:00:27.237943+00:00
[2023-12-05T14:00:28.577+0000] {standard_task_runner.py:57} INFO - Started process 15400 to run task
[2023-12-05T14:00:28.583+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_hook_v2', 'upload_to_s3', 'manual__2023-12-05T14:00:27.237943+00:00', '--job-id', '357', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_with_hook.py', '--cfg-path', '/tmp/tmpfry0buht']
[2023-12-05T14:00:28.587+0000] {standard_task_runner.py:85} INFO - Job 357: Subtask upload_to_s3
[2023-12-05T14:00:28.657+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_with_hook_v2.upload_to_s3 manual__2023-12-05T14:00:27.237943+00:00 [running]> on host 0c998a8be895
[2023-12-05T14:00:28.790+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='debora' AIRFLOW_CTX_DAG_ID='dag_with_hook_v2' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2023-12-05T14:00:27.237943+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-05T14:00:27.237943+00:00'
[2023-12-05T14:00:28.802+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:206 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-12-05T14:00:28.815+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-12-05T14:00:28.830+0000] {logging_mixin.py:154} INFO - connected to postgres
[2023-12-05T14:00:28.842+0000] {dag_with_postgres_with_hook.py:29} INFO - Saved get_orders_2023-12-05T14:00:27.237943+00:00
[2023-12-05T14:00:28.843+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-12-05T14:00:28.859+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_hook_v2, task_id=upload_to_s3, execution_date=20231205T140027, start_date=20231205T140028, end_date=20231205T140028
[2023-12-05T14:00:28.918+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-05T14:00:28.942+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
