[2023-12-05T00:08:05.771+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_v03.insert_post_ scheduled__2023-12-04T00:00:00+00:00 [queued]>
[2023-12-05T00:08:05.782+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_v03.insert_post_ scheduled__2023-12-04T00:00:00+00:00 [queued]>
[2023-12-05T00:08:05.782+0000] {taskinstance.py:1361} INFO - Starting attempt 5 of 6
[2023-12-05T00:08:05.801+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_post_> on 2023-12-04 00:00:00+00:00
[2023-12-05T00:08:05.806+0000] {standard_task_runner.py:57} INFO - Started process 11101 to run task
[2023-12-05T00:08:05.810+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_v03', 'insert_post_', 'scheduled__2023-12-04T00:00:00+00:00', '--job-id', '302', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres.py', '--cfg-path', '/tmp/tmp4o489f61']
[2023-12-05T00:08:05.813+0000] {standard_task_runner.py:85} INFO - Job 302: Subtask insert_post_
[2023-12-05T00:08:05.870+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_with_postgres_v03.insert_post_ scheduled__2023-12-04T00:00:00+00:00 [running]> on host a859eb4bf49d
[2023-12-05T00:08:05.961+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='debora' AIRFLOW_CTX_DAG_ID='dag_with_postgres_v03' AIRFLOW_CTX_TASK_ID='insert_post_' AIRFLOW_CTX_EXECUTION_DATE='2023-12-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-04T00:00:00+00:00'
[2023-12-05T00:08:05.962+0000] {sql.py:274} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2023-12-04', 'dag_with_postgres_v03')

        
[2023-12-05T00:08:05.973+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-12-05T00:08:05.983+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-12-05T00:08:05.993+0000] {sql.py:418} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2023-12-04', 'dag_with_postgres_v03')

        , parameters: None
[2023-12-05T00:08:05.996+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "dag_runs_pkey"
DETAIL:  Key (dt, dag_id)=(2023-12-04, dag_with_postgres_v03) already exists.

[2023-12-05T00:08:06.007+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_v03, task_id=insert_post_, execution_date=20231204T000000, start_date=20231205T000805, end_date=20231205T000806
[2023-12-05T00:08:06.026+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 302 for task insert_post_ (duplicate key value violates unique constraint "dag_runs_pkey"
DETAIL:  Key (dt, dag_id)=(2023-12-04, dag_with_postgres_v03) already exists.
; 11101)
[2023-12-05T00:08:06.065+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-05T00:08:06.086+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
